# Generated by Django 5.0.6 on 2024-06-23 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2,  default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
