# Generated by Django 5.0.6 on 2024-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
