# Generated by Django 5.0.6 on 2024-06-30 08:25

from django.db import migrations, models
import django.utils.timezone 


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_userbehavior_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
